# Generated by Django 2.2.16 on 2022-04-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220412_2253'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follow',
        ),
    ]
